[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

[etherscan]
arc_testnet = { key = "${ETHERSCAN_API_KEY}" }

